matches:
#  ../Textexpander-Archive/Numerals.textexpander
  - trigger: "\\(1)"
    replace: "①" 
  - trigger: "\\(2)"
    replace: "②" 
  - trigger: "\\(3)"
    replace: "③" 
  - trigger: "\\(4)"
    replace: "④" 
#  ../Textexpander-Archive/Pinyin.textexpander
  - trigger: "a|!"
    replace: "ā" 
  - trigger: "a|@"
    replace: "á" 
  - trigger: "a|#"
    replace: "ǎ" 
  - trigger: "a\\$"
    replace: "à" 
  - trigger: "e|!"
    replace: "ē" 
  - trigger: "e|@"
    replace: "é" 
  - trigger: "e|#"
    replace: "ě" 
  - trigger: "e|$"
    replace: "è" 
  - trigger: "i|!"
    replace: "ī" 
  - trigger: "i|@"
    replace: "í" 
  - trigger: "i|$"
    replace: "ì" 
  - trigger: "i|#"
    replace: "ǐ" 
  - trigger: "o|!"
    replace: "ō" 
  - trigger: "o|@"
    replace: "ó" 
  - trigger: "o|#"
    replace: "ǒ" 
  - trigger: "o|$"
    replace: "ò" 
  - trigger: "u|!"
    replace: "ū" 
  - trigger: "u|@"
    replace: "ú" 
  - trigger: "u|#"
    replace: "ǔ" 
  - trigger: "u|$"
    replace: "ù" 
  - trigger: "u:|!"
    replace: "ǖ" 
  - trigger: "u:|@"
    replace: "ǘ" 
  - trigger: "u:|#"
    replace: "ǚ" 
  - trigger: "u:|$"
    replace: "ǜ" 
#  ../Textexpander-Archive/Dashes and Spaces.textexpander
  - trigger: "\\--"
    replace: "—" 
  - trigger: "\\mdash"
    replace: "—" 
  - trigger: "\\emdash"
    replace: "—" 
  - trigger: "\\ndash"
    replace: "–" 
  - trigger: "\\endash"
    replace: "–" 
  - trigger: "\\zwsp"
    replace: "​" 
  - trigger: "\\bul"
    replace: "•" 
  - trigger: "\\check"
    replace: "✓" 
#  ../Textexpander-Archive/Arrows.textexpander
  - trigger: "\\rarrow"
    replace: "→" 
  - trigger: "\\larrow"
    replace: "←" 
  - trigger: "\\uarrow"
    replace: "↑" 
  - trigger: "\\darrow"
    replace: "↓" 
  - trigger: "\\lrarrow"
    replace: "⟷" 
#  ../Textexpander-Archive/Clipboard Commands.textexpander

#  ../Textexpander-Archive/Math & Greek.textexpander
  - trigger: "\\times"
    replace: "×" 
  - trigger: "\\subset"
    replace: "⊂" 
  - trigger: "\\mu"
    replace: "μ" 
  - trigger: "\\pm"
    replace: "±" 
  - trigger: "\\int"
    replace: "∫" 
  - trigger: "\\inf"
    replace: "∞" 
  - trigger: "\\sum"
    replace: "∑" 
  - trigger: "\\Theta"
    replace: "ϴ" 
  - trigger: "\\setin"
    replace: "∈" 
  - trigger: "\\Delta"
    replace: "∆" 
  - trigger: "\\deg"
    replace: "º" 
  - trigger: "\\cap"
    replace: "∩" 
  - trigger: "\\cup"
    replace: "∪" 
  - trigger: "\\leq"
    replace: "≤" 
  - trigger: "\\geq"
    replace: "≥" 
  - trigger: "\\beta"
    replace: "β" 
  - trigger: "\\approx"
    replace: "≈" 
  - trigger: "E-|"
    replace: "Ξ" 
  - trigger: "\\forall"
    replace: "∀" 
